### ISSUE TITLE
14장 Zombie 서바이버 프로젝트 의존성문제

### ISSUE THREAD

**Issue by MutesK** [IJEMIN/Unity-Programming-Essence#1]
패키지 매니저랑 Cinemachine쪽에서 서도 다른 에러로 에러 메세지를 뱉고 있습니다.

1. Package-Manager
```
An error occurred while resolving packages:
  Project has invalid dependencies:
    com.unity.package-manager-ui: Package [com.unity.package-manager-ui@2.1.1] cannot be found
```
2. Cinemachine
```
Assembly has reference to non-existent assembly 'GUID:f06555f75b070af458a003d92f9efb00' (Packages/com.unity.cinemachine/Runtime/com.unity.cinemachine.asmdef)
```

해결방법 부탁드립니다. ㅠㅠ

**Comment by IJEMIN** [comment]
- 프로젝트를 유니티 2019.1(권장) 또는 그 이후의 버전으로 열어보세요.

Cinemachine 패키지는 Timeline 패키지를 필요로 합니다. 책의 예제는 유니티 2019.1 버전으로 만들어졌고, 유니티 2019.1 버전은 Timeline 에디터가 내장되어 있습니다.

유니티 2019.1이 아닌, 유니티 2018 버전대로 열면 의존 패키지가 존재하지 않다는 에러가 납니다.

위 해결 방법을 시도한 후 결과를 알려주세요 :)

**Comment by MutesK** [comment]
넵 2019.1 버전으로 업그레이드 한후, 다시 시도해보니 잘되네요. 감사합니다.
