### ISSUE TITLE
<레트로의 유니티 게임 프로그래밍 에센스> 오탈자 신고

### ISSUE THREAD

**Issue by Leon-iii** [IJEMIN/Unity-Programming-Essence#10]
안녕하세요. 알라딘에서 E-book 구매 후 읽던 중에 사소한 오타를 발견해 신고합니다.

신고 내용은 686p 16.1 다형성 파트, 4번째 줄 'LivignEntity' 입니다.

감사합니다.

**Comment by Leon-iii** [comment]
덧붙이자면 2021 개정판입니다.

**Comment by IJEMIN** [comment]
감사합니다. 오탈자 목록에 추가하고 다음 판본에 반영할 수 있도록 할게요

**Comment by IJEMIN** [comment]
3쇄에 반영될 예정입니다~
