### ISSUE TITLE
Zombie 서바이퍼 프로젝트 메모리 문제

### ISSUE THREAD

**Issue by mskim1024** [IJEMIN/Unity-Programming-Essence#2]
좀비 서바이버 프로젝트에서 라이팅 관련 셋팅을 따라하던 중에 다음과 같이 에러가 발생합니다.

Clustering job failed for system: 0xb5ea163a1820d905b0387a2d8fb92bda, error: 4 - 'Out of memory loading input data.'.
Please close applications to free memory, optimize the scene, increase the size of the pagefile or use a system with more memory.
Total memory (physical and paged): 71913MB.

메모리 관련 문제인 것은 알겠는데 정확히 어떤게 오류를 발생시키는지 해결 방법이 무엇인지
궁금합니다...

**Comment by IJEMIN** [comment]
해당 에러의 로그는 라이팅을 굽기 위한 시스템 리소스가 충분하지 않다는 내용입니다.
씬이 넒고 커서 그런 경우도 있고, 실제로는 유니티 에디터의 자체적인 버그로, 시스템 리소스가 충분해도 충분하지 않다는 로그가 뜨는 경우도 있어요.

일단 유니티를 재시작후, 라이팅 설정 윈도우에서 설정에서 Auto를 체크 해제하고, 책의 라이팅 과정을 다시 시도해보세요. 특히 Baked Global Illumination은 꼭 체크 해제 해주세요.

여전히 안된다면 사용한 유니티 버전과 운영체제 환경을 알려주시겠어요?

**Comment by mskim1024** [comment]
아, 재부팅 후 다른 곳에 순정 폴더를 복사 후 실행시키니까 제대로 동작합니다.
감사합니다.

**Comment by IJEMIN** [comment]
다행이네요 :) 특별한 처리없이 문제가 해결된 것으로 보이니 이슈 닫겠습니다.
