### ISSUE TITLE
닷지 탄알이 움직이지 않아요.

### ISSUE THREAD

**Issue by mullfirst** [IJEMIN/Unity-Programming-Essence#4]
우선 탄알 생성기 1개 만들고, 실행하면 탄알이 생성/소멸은 되는데 날아가지가 않네요.

Start 함수에서 Update로 바꾸면 움직이는데, 다운받은 예제 실행하면 Start인데도 또 정상적으로 동작하구요.

예제받은 bullet.cs를 가져와도 역시나 움직이지가 않아요. 이해가 안됩니다.

Start함수는 시작 시 1번만 실행되잖아요

**Comment by IJEMIN** [comment]
정확한 문제를 파악할 수 있도록 작성한 Bullet 스크립트의 내용을 여기에 첨부해주세요.
현재로서 예상되는 문제로는 프리팹이 된 Bullet 게임 오브젝트에 Bullet.cs 스크립트가 누락된 문제가 있을 것 같습니다.

**Comment by mullfirst** [comment]
Bullet을 처음부터 다시 만들었더니, 정상 동작해요.
감사합니다.

**Comment by IJEMIN** [comment]
문제가 해결된 것으로 보이므로 이슈 닫겠습니다.
