### ISSUE TITLE
[12장] 잘못된 수치값 제보 p.491

### ISSUE THREAD

**Issue by Mincl** [IJEMIN/Unity-Programming-Essence#6]
- **[과정 03] 게임 재시작 안내 텍스트 만들기**의 **3번째 항목**의 ```Restart Text의 Rect Transform 컴포넌트의 Pos Y 값을 -40으로 변경```이라고 되어 있는 부분은 환경에 따라 설정해야 하는 값이 달라질 수 있습니다. 앞서 '게임오버 텍스트'의 Anchor를 top-center로 설정을 하는데, 이때 Pos Y 값이 0이 된다는 보장이 없습니다. 실제로 예시를 따라 하니 '게임오버 텍스트'와 위치가 겹칩니다. '게임오버 텍스트'의 Pos Y값에서 -40을 더한 값이 되어야 할 것 같습니다.

**Comment by IJEMIN** [comment]
Alt를 누른 상태에서는 스냅핑이 활성화되므로 Anchor 값 뿐만 아니라 Position 값들도 변경됩니다. 따라서 Pos Y 값도 앵커값이 변화는 것과 동시에 0이 되지 않나요?

**Comment by Mincl** [comment]
@IJEMIN Alt로 스냅핑을 해도 0이 안됩니다...ㅠㅠ

**Comment by IJEMIN** [comment]
책 텍스트는 정상입니다. 제가 코멘트에서 잘못설명했군요.

Alt 만 누르면 스냅핑이 활성화되어 위치값이 변경되는 것은 맞으나 피벗 값은 위쪽으로 변경되지 않습니다. 따라서 눈으로 보이는 레이아웃 상으로는 UI요소가 위쪽에 붙게 되나, Position의 Y 값은 0이 되지 않습니다.

따라서 490페이지의 명시대로 Alt만 누르는게 아니라, Alt-Shift를 같이 눌러야 합니다. Shift를 누르면 피벗값이 함께 해당 방향으로 몰아지도록 변경됩니다. 그러면 좌표를 계산하기 위한 피벗이 함께 위쪽으로 붙으므로, Position의 Y 값이 0으로 출력될 것입니다.

따라서 490 페이지의 과정에서, Alt는 물론 Shift를 함께 눌러 앵커 프리셋을 사용해주세요.
