### ISSUE TITLE
191p ~ 192p 질문 있습니다!

### ISSUE THREAD

**Issue by jjayun** [IJEMIN/Unity-Programming-Essence#9]
Animal 클래스가 MonoBehaviour 클래스를 상속하여도 Zoo 클래스에서 new 로 Animal 클래스의 인스턴스 생성이 되는 것 같아요!!

버전이 높아져서 MonoBehaviour 를 상속한 클래스도 new로 객체를 생성할 수 있게 된 것인지 궁금합니다!

**Comment by IJEMIN** [comment]
MonoBehaviour를 상속한 클래스의 인스턴스를 new로 생성하는 행위 자체는 실행되지만, 게임 오브젝트의 컴포넌트로서 생성되지 못하므로 정상적으로 동작하지 못하고, 씬에서 확인할 수 없어요!
